server_host = "10.1.5.2"
server_port = 80

[attack]
legitimate_client_ip = "10.1.4.2"
gateway_ext_ip = "10.1.1.3"
gateway_int_ip = "10.1.5.3"
spoof_blacklist = [
    "10.1.1.2",  # router
    "10.1.2.3",  # router
    "10.1.3.3",  # router
    "10.1.4.3",  # router
]

[legitimate]
rate = 2
resources = [
    "1.html",
    "cmFuZG9tdXJs",
]
